# Generated by Django 4.2.1 on 2023-05-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_tag_scope_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Объем', 'verbose_name_plural': 'Объем'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='aricles',
        ),
    ]
