# Generated by Django 4.2.1 on 2023-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_group_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher', verbose_name='Учителя'),
        ),
    ]
