# Generated by Django 4.2.1 on 2023-05-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_teacherstudent_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='teachers',
            field=models.ManyToManyField(related_name='Учителя', to='school.teacher'),
        ),
    ]
