# Generated by Django 4.2.1 on 2023-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_teacherstudent_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='Учителя', to='school.teacher'),
        ),
        migrations.DeleteModel(
            name='TeacherStudent',
        ),
    ]
