# Generated by Django 4.2.1 on 2023-05-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_student_teacher_student_teachers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
